#!/usr/bin/env perl

use strict;
use FindBin;
use lib ("$FindBin::Bin/PerlLib");
use Fasta_reader;
use Getopt::Long qw(:config posix_default no_ignore_case bundling pass_through);
use strict;
use Carp;
use Cwd;
use HPC::GridRunner;
use List::Util qw (shuffle);
use File::Basename;


my $usage =  <<_EOH_;

############################# Options ##################################################################################
#
# Required:
#
#   --query_fasta|Q <string>       query multiFastaFile (full or relative path)
#
#   --cmd_template|T <string>      program command line template:   eg. "/path/to/prog [opts] __QUERY_FILE__ [other opts]"
#
#   --seqs_per_bin|N <int>                      number of sequences per partition.
# 
#   --out_dir|O <string>           output directory 
#
# Optional:
#
#   --prep_only|X                  partion data and create cmds list, but don't launch on the grid.
#
#
###################### Process Args and Options ########################################################################


_EOH_

    
    ;

my $query_fasta_file;
my $program_cmd_template;
my $bin_size;
my $help = 0;
my $CMDS_ONLY = 0;
my $out_dir;
my $prep_only_flag = 0;

&GetOptions('query_fasta|Q=s' => \$query_fasta_file,
            'cmd_template|T=s' => \$program_cmd_template,
            'seqs_per_bin|N=i' => \$bin_size,
            'out_dir|O=s' => \$out_dir,
            'prep_only|X' => \$prep_only_flag,
    );



if ($opt_h) {
    die $usage;
}

unless ($query_fasta_file && $program_cmd_template && $bin_size && $out_dir) {
    die $usage;
}

unless ($queryFile =~ /^\//) {
    $queryFile = cwd() . "/$queryFile";
}


unless ($program_cmd_template =~ /__QUERY_FILE__/) {
    die "Error, program cmd template must include '__QUERY_FILE__' placeholder in the command";
}


## Create files to search

my $fastaReader = new Fasta_reader($queryFile);

my @searchFileList;

my $count = 0;
my $current_bin = 1;

mkdir $out_dir or die "Error, cannot mkdir $out_dir";

my $bindir = "$out_dir/grp_" . sprintf ("%04d", $current_bin);
mkdir ($bindir) or die "Error, cannot mkdir $bindir";



while (my $fastaSet = &get_next_fasta_entries($fastaReader, $num_seqs_per_job) ) {
    
	$count++;
	
    my $filename = "$bindir/$count.fa";
                
    push (@searchFileList, $filename);
	
    open (TMP, ">$filename") or die "Can't create file ($filename)\n";
    print TMP $fastaSet;
    close TMP;
    chmod (0666, $filename);
    	
	if ($count % $bin_size == 0) {
		# make a new bin:
		$current_bin++;
		$bindir = "$out_dir/grp_" . sprintf ("%04d", $current_bin);
		mkdir ($bindir) or die "Error, cannot mkdir $bindir";
	}
}

print STDERR "Sequences to search: @searchFileList\n";
my $numFiles = @searchFileList;
print STDERR "There are $numFiles blast search jobs to run.\n";

my $curr_dir = cwd;

if  ($numFiles) {
    
    my @cmds;
    ## formulate blast commands:
    foreach my $searchFile (@searchFileList) {
        $searchFile = "$curr_dir/$searchFile";
        
        my $cmd = $program_cmd_template;
        $cmd =~ s/__QUERY_FILE__/$searchFile/g;
        

        $cmd .= " > $searchFile.OUT ";
		
        unless ($CMDS_ONLY) {
			$cmd .= " 2>$searchFile.ERR";
		}
        push (@cmds, $cmd);
    }
    
	
    @cmds = shuffle(@cmds);

    my $cmds_per_node;
    if ($CMDS_PER_NODE) {
        $cmds_per_node = $CMDS_PER_NODE;
    }
    else {
        $cmds_per_node = int ( scalar(@cmds) / 400); # split job across complete set of nodes available.
        if ($cmds_per_node < 1) {
            # use 10 as default.
            $cmds_per_node = 1;
        }
    }
    

	open (my $fh, ">cmds.list") or die $!;
	foreach my $cmd (@cmds) {
		print $fh "$cmd\n";
	}
	close $fh;
	
	unless ($CMDS_ONLY) {
		my $bsubber = new Bsub({cmds=>\@cmds,
								log_dir => $out_dir,
								cmds_per_node => $cmds_per_node,
								queue => $queue,
								memory => $memory,
							}
			);
		
		$bsubber->bsub_jobs();
		
	}

} else {
    print STDERR "Sorry, no searches to perform.  Results already exist here\n";
}
## Cleanup

exit(0);


####
sub get_next_fasta_entries {
    my ($fastaReader, $num_seqs) = @_;


    my $fasta_entries_txt = "";
    
    for (1..$num_seqs) {
        my $seq_obj = $fastaReader->next();
        unless ($seq_obj) {
            last;
        }

        my $entry_txt = $seq_obj->get_FASTA_format();
        $fasta_entries_txt .= $entry_txt;
    }

    return($fasta_entries_txt);
}
